train_sentences = [
    "I wanna go to store",
    "I am UITer",
    "I am student",
    "I go to school",
    "I am gay",
    "I love you",
    "I love CS115",
    "Nguyen Thien Bao",
    "Dong Quoc Thang",
    "Tran Le Minh Nhat",
    "My name is Bao",
    "My name is Thang",
    "My name is Nhat",
    "I enjoy learning AI",
]
